//-----------------------------------------------------------------------------
//
// LEDTREES: adapter from the LedPixelController stubs to the ledtrees_ledpixel
// component.
//
// The whole output path to the strip (SPI, the LedTask and FeedTask tasks, the
// playback buffers, feeding from SD, the remap and the colour correction) lives
// in a separate IDF component - the ledtrees-idf-components repository,
// components/ledtrees_ledpixel. What is left here is unwrapping the managed
// arrays into a pointer and a size, and translating lt_led_status_t into an
// HRESULT.
//
// This implementation is written by hand, unlike interoplib.cpp/.h and
// *_mshl.cpp - those are generated by building the managed project and come
// ready in ledtrees-esp32/nanoframework/src/interoplib/Stubs/interoplib. They
// have to be copied from there rather than edited here: the method_lookup table
// is indexed by the ordinal of the method in the assembly, so a hand written
// insertion shifts the indices and calls end up in the wrong slots.
//
//-----------------------------------------------------------------------------

#include "interoplib.h"
#include "interoplib_interoplib_LedPixelController.h"

#include <ledtrees_ledpixel.h>

using namespace interoplib::interoplib;

// LT_LED_ERR_STATE is the former S_FALSE (the state does not allow it) and
// LT_LED_ERR_PARAM the former CLR_E_INVALID_PARAMETER (the arguments do not add
// up). The split is the same as it was in the body of each method before the
// code was moved out.
static HRESULT ToHResult(lt_led_status_t status)
{
    switch (status)
    {
        case LT_LED_OK:
            return S_OK;
        case LT_LED_ERR_PARAM:
            return CLR_E_INVALID_PARAMETER;
        default:
            return S_FALSE;
    }
}

void LedPixelController::NativeInit(
    signed int mosiPin,
    signed int misoPin,
    signed int clkPin,
    signed int csPin,
    signed int pixelCount,
    uint8_t red,
    uint8_t green,
    uint8_t blue,
    uint8_t powerLimitPercent,
    HRESULT &hr)
{
    lt_led_config_t config;
    config.mosiPin = mosiPin;
    config.misoPin = misoPin;
    config.clkPin = clkPin;
    config.csPin = csPin;
    config.pixelCount = pixelCount;
    config.initRed = red;
    config.initGreen = green;
    config.initBlue = blue;
    // The power limiter, as the factory fraction from the assembly configuration
    // (ledtrees-esp32 docs/assembly.md); the component reads 0 or anything >= 100
    // as "no limiter".
    config.powerLimitPercent = powerLimitPercent;

    hr = ToHResult(lt_led_init(&config));
}

void LedPixelController::NativeSetSource(
    CLR_RT_TypedArray_UINT8 path,
    unsigned int header,
    uint16_t frameSize,
    uint16_t countFrames,
    uint16_t startFrame,
    HRESULT &hr)
{
    hr = ToHResult(
        lt_led_set_source(path.GetBuffer(), path.GetSize(), header, frameSize, countFrames, startFrame));
}

void LedPixelController::NativeSetBrightness( uint8_t value, HRESULT &hr )
{
    hr = ToHResult(lt_led_set_brightness(value));
}

signed int LedPixelController::NativeGetPlayPosition( HRESULT &hr )
{
    hr = S_OK;
    return lt_led_get_play_position();
}

signed int LedPixelController::NativeGetFeedReadErrors( HRESULT &hr )
{
    hr = S_OK;
    return lt_led_get_feed_read_errors();
}

// The per-node remap table (docs/node-calibration.md). An empty array clears the
// remap; a malformed length or index is rejected by the component, which leaves
// the table in force untouched.
void LedPixelController::NativeSetRemap( CLR_RT_TypedArray_UINT8 param0, HRESULT &hr )
{
    hr = ToHResult(lt_led_set_remap(param0.GetBuffer(), param0.GetSize()));
}

// Highlighting during a calibration pass: a range of physical pixels on the line
// blinks between red and black. count == 0 clears the highlight.
void LedPixelController::NativeSetHighlight( uint8_t line, uint16_t start, uint16_t count, uint16_t blinkMs, HRESULT &hr )
{
    hr = ToHResult(lt_led_set_highlight(line, start, count, blinkMs));
}

// Changing the power limiter fraction on the fly. In normal operation the value
// arrives once in NativeInit from the assembly configuration; this path is for
// service tuning and for future control from MAIN.
void LedPixelController::NativeSetPowerLimit( uint8_t percent, HRESULT &hr )
{
    hr = ToHResult(lt_led_set_power_limit(percent));
}

// Number of frames output with the brightness cut by the limiter, over the
// uptime.
signed int LedPixelController::NativeGetPowerLimitedFrames( HRESULT &hr )
{
    hr = S_OK;
    return lt_led_get_power_limited_frames();
}

// Playback colour filters (ledtrees-esp32 docs/color-filters.md): a 3x3 Q8
// matrix and a luma to RGB palette. Empty arrays clear them; malformed lengths
// are rejected silently by the component, which leaves the tables in force
// untouched (validation happens on the managed side, as for SetRemap).

void LedPixelController::NativeSetColorMatrix( CLR_RT_TypedArray_INT16 m9q8, HRESULT &hr )
{
    hr = ToHResult(lt_led_set_color_matrix(m9q8.GetBuffer(), m9q8.GetSize()));
}

void LedPixelController::NativeSetColorLut( CLR_RT_TypedArray_UINT8 lut, HRESULT &hr )
{
    hr = ToHResult(lt_led_set_color_lut(lut.GetBuffer(), lut.GetSize()));
}

void LedPixelController::NativeSetColorLutEnabled( bool enabled, HRESULT &hr )
{
    hr = ToHResult(lt_led_set_color_lut_enabled(enabled ? 1 : 0));
}

// Runtime colour correction (ledtrees-esp32 docs/color-filters.md, phase 3):
// parameters rather than a table, since the native side applies the brightness
// before the gamma itself. gammaQ8 == 0 resets to the compile time defaults;
// out of range values are rejected silently by the component (S_FALSE), and the
// managed wrapper validates the same bounds up front.
void LedPixelController::NativeSetOutputCorrection( uint16_t gammaQ8, uint8_t blackPoint, uint16_t wbR, uint16_t wbG, uint16_t wbB, int16_t contrastQ8, HRESULT &hr )
{
    hr = ToHResult(lt_led_set_output_correction(gammaQ8, blackPoint, wbR, wbG, wbB, contrastQ8));
}

// Statistics for composing a playback frame since the last call, packed as
// (avg << 16) | max in microseconds; 0 means there were no frames. This is
// diagnostics: the IDF logs are compiled out of the firmware, so the native side
// accumulates and the managed side logs.
signed int LedPixelController::NativeGetComposeStats( HRESULT &hr )
{
    hr = S_OK;
    return lt_led_get_compose_stats();
}

// Re-anchoring SyncPlay: check our own position against the frame the group is
// playing right now. Returns the correction applied, in frames; 0 means we are
// in phase, or a very close correction is already under way.
signed int LedPixelController::NativeSyncPlayPosition( uint16_t groupFrame, HRESULT &hr )
{
    hr = S_OK;
    return lt_led_sync_play_position(groupFrame);
}

void LedPixelController::NativePrepareForPlay( uint16_t frame, CLR_RT_TypedArray_UINT8 data, HRESULT &hr )
{
    hr = ToHResult(lt_led_prepare_for_play(frame, data.GetBuffer(), data.GetSize()));
}

void LedPixelController::NativeStartPlay( uint16_t countFrames, uint8_t outputFps, uint8_t contentFps, uint16_t transition, HRESULT &hr )
{
    hr = ToHResult(lt_led_start_play(countFrames, outputFps, contentFps, transition));
}

// NOTE on the contract: this writes the buffer that is NOT playing, without a
// Stop or Join and without any locking - during playback the same data is
// maintained by the feeding task. It is only safe when called on a STOPPED
// player. At the moment the managed side does not call this entry point at all
// (the LedPixelController.WriteToPlayBuffer wrapper has no callers).
void LedPixelController::NativeWriteToPlayBuffer( uint16_t frame, CLR_RT_TypedArray_UINT8 data, HRESULT &hr )
{
    hr = ToHResult(lt_led_write_to_play_buffer(frame, data.GetBuffer(), data.GetSize()));
}

void LedPixelController::NativeWrite( CLR_RT_TypedArray_UINT8 data, HRESULT &hr )
{
    hr = ToHResult(lt_led_write(data.GetBuffer(), data.GetSize()));
}

// Fill with a colour, fading from the current state of the strip (transition in
// milliseconds; 0 is immediate). Blocks the calling CLR thread for the duration
// of the fade.
void LedPixelController::NativeSetFull( uint8_t red, uint8_t green, uint8_t blue, uint16_t transition, HRESULT &hr )
{
    hr = ToHResult(lt_led_set_full(red, green, blue, transition));
}

void LedPixelController::NativeSetPixel( uint8_t line, uint16_t cell, uint8_t red, uint8_t green, uint8_t blue, HRESULT &hr )
{
    hr = ToHResult(lt_led_set_pixel(line, cell, red, green, blue));
}
