//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------

#include "interoplib.h"

// clang-format off

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_interoplib_interoplib_Crypto::NativeSha256Begin___STATIC__BOOLEAN,
    Library_interoplib_interoplib_Crypto::NativeSha256Update___STATIC__BOOLEAN__SZARRAY_U1__I4,
    Library_interoplib_interoplib_Crypto::NativeSha256Final___STATIC__BOOLEAN__SZARRAY_U1,
    Library_interoplib_interoplib_Crypto::NativeVerifyP256___STATIC__BOOLEAN__SZARRAY_U1__SZARRAY_U1__SZARRAY_U1,
    Library_interoplib_interoplib_FrameDecoder::NativeDecodeFrame___STATIC__I4__SZARRAY_U1__I4__I4__SZARRAY_U1__SZARRAY_U1__U2,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_interoplib_interoplib_LedPixelController::NativeInit___STATIC__VOID__I4__I4__I4__I4__I4__U1__U1__U1,
    Library_interoplib_interoplib_LedPixelController::NativeSetBrightness___STATIC__VOID__U1,
    Library_interoplib_interoplib_LedPixelController::NativePrepareForPlay___STATIC__VOID__U2__SZARRAY_U1,
    Library_interoplib_interoplib_LedPixelController::NativeStartPlay___STATIC__VOID__U2__U1__U2,
    Library_interoplib_interoplib_LedPixelController::NativeWriteToPlayBuffer___STATIC__VOID__U2__SZARRAY_U1,
    Library_interoplib_interoplib_LedPixelController::NativeSetSource___STATIC__VOID__SZARRAY_U1__U4__U2__U2__U2,
    Library_interoplib_interoplib_LedPixelController::NativeWrite___STATIC__VOID__SZARRAY_U1,
    Library_interoplib_interoplib_LedPixelController::NativeSetFull___STATIC__VOID__U1__U1__U1__U2,
    Library_interoplib_interoplib_LedPixelController::NativeSetPixel___STATIC__VOID__U1__U2__U1__U1__U1,
    Library_interoplib_interoplib_LedPixelController::NativeGetPlayPosition___STATIC__I4,
    Library_interoplib_interoplib_LedPixelController::NativeSyncPlayPosition___STATIC__I4__U2,
    Library_interoplib_interoplib_LedPixelController::NativeGetFeedReadErrors___STATIC__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_interoplib_interoplib_Ota::NativeFirmwareBegin___STATIC__BOOLEAN__I4,
    Library_interoplib_interoplib_Ota::NativeFirmwareWrite___STATIC__BOOLEAN__SZARRAY_U1__I4,
    Library_interoplib_interoplib_Ota::NativeFirmwareEnd___STATIC__BOOLEAN,
    Library_interoplib_interoplib_Ota::NativeGetRunningSha256___STATIC__BOOLEAN__SZARRAY_U1,
    Library_interoplib_interoplib_Ota::NativeStageBegin___STATIC__BOOLEAN__I4,
    Library_interoplib_interoplib_Ota::NativeStageWrite___STATIC__BOOLEAN__SZARRAY_U1__I4,
    Library_interoplib_interoplib_Ota::NativeStageCommit___STATIC__BOOLEAN__U4,
    Library_interoplib_interoplib_Ota::NativeCommitFull___STATIC__BOOLEAN,
    Library_interoplib_interoplib_Ota::NativeConfirm___STATIC__BOOLEAN,
    Library_interoplib_interoplib_Ota::NativeGetState___STATIC__U1,
    Library_interoplib_interoplib_Ota::NativeIsPendingConfirm___STATIC__BOOLEAN,
    Library_interoplib_interoplib_Ota::NativeReadRunningFirmware___STATIC__I4__I4__SZARRAY_U1__I4,
    Library_interoplib_interoplib_Ota::NativeReadDeploy___STATIC__I4__I4__SZARRAY_U1__I4,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_interoplib_interoplib_Utilities::NativeGetBaseMac___STATIC__VOID__SZARRAY_U1,
    Library_interoplib_interoplib_Utilities::NativeCrc32___STATIC__U4__U4__SZARRAY_U1__I4__I4,
    Library_interoplib_interoplib_Utilities::NativeSdProbe___STATIC__I4__U1__U2__SZARRAY_U1,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_interoplib =
{
    "interoplib",
    0x8BC1353F,
    method_lookup,
    { 2, 0, 0, 0 }
};

// clang-format on
